/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.navbar-inverse[_ngcontent-%COMP%]   .navbar-brand[_ngcontent-%COMP%] {\r\n    color: #fff;\r\n}\r\n\r\n.navbar-inverse[_ngcontent-%COMP%]   .glyphicon[_ngcontent-%COMP%] {\r\n    margin-right: 10px;\r\n}\r\n\r\nmd-button-toggle[_ngcontent-%COMP%]   .md-button-toggle-label[_ngcontent-%COMP%] {\r\n    margin-bottom: 0;\r\n}\r\n\r\n.md-button-toggle-checked[_ngcontent-%COMP%]   .md-button-toggle-label-content[_ngcontent-%COMP%] {\r\n    background-color: #b0bec5;\r\n}'];
//# sourceMappingURL=navigation.css.shim.ngstyle.js.map