/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.search-container[_ngcontent-%COMP%] {\r\n    float: right;\r\n}\r\n\r\n.row[_ngcontent-%COMP%] {\r\n    margin: 0;\r\n}\r\n\r\n.table[_ngcontent-%COMP%] {\r\n    margin-bottom: 15px;\r\n}'];
//# sourceMappingURL=search.css.shim.ngstyle.js.map