/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/material/core/compatibility/default-mode';
import * as import6 from '@angular/material/core/ripple/ripple';
import * as import7 from '@angular/material/button/button';
import * as import8 from '@angular/material/card/card';
import * as import9 from '@angular/material/chips/chip-list';
import * as import10 from '@angular/material/checkbox/checkbox';
import * as import11 from '@angular/material/core/line/line';
import * as import12 from '@angular/material/grid-list/grid-list';
import * as import13 from '@angular/forms/src/directives';
import * as import14 from '@angular/forms/src/form_providers';
import * as import15 from '@angular/material/core/platform/index';
import * as import16 from '@angular/material/input/input';
import * as import17 from '@angular/material/list/list';
import * as import18 from '@angular/material/progress-bar/progress-bar';
import * as import19 from '@angular/material/progress-spinner/progress-spinner';
import * as import20 from '@angular/material/core/portal/portal-directives';
import * as import21 from '@angular/material/core/overlay/overlay-directives';
import * as import22 from '@angular/material/select/index';
import * as import23 from '@angular/material/core/a11y/index';
import * as import24 from '@angular/material/sidenav/sidenav';
import * as import25 from '@angular/material/core/observe-content/observe-content';
import * as import26 from '@angular/material/tabs/tab-group';
import * as import27 from '@angular/material/toolbar/toolbar';
import * as import28 from '@angular/material/core/projection/projection';
import * as import29 from '@angular/material/core/rtl/dir';
import * as import30 from '@angular/material/button-toggle/button-toggle';
import * as import31 from '@angular/material/dialog/index';
import * as import32 from '@angular/http/src/http_module';
import * as import33 from '@angular/material/icon/icon';
import * as import34 from '@angular/material/menu/menu';
import * as import35 from '@angular/material/radio/radio';
import * as import36 from '@angular/material/slider/slider';
import * as import37 from '@angular/material/slide-toggle/slide-toggle';
import * as import38 from '@angular/material/snack-bar/snack-bar';
import * as import39 from '@angular/material/tooltip/tooltip';
import * as import40 from '@angular/material/module';
import * as import41 from './core/core.module';
import * as import42 from './shared/shared.module';
import * as import43 from './weatherList/weatherList.module';
import * as import44 from './map/map.module';
import * as import45 from '@angular/common/src/localization';
import * as import46 from '@angular/core/src/application_init';
import * as import47 from '@angular/core/src/testability/testability';
import * as import48 from '@angular/core/src/application_ref';
import * as import49 from '@angular/core/src/linker/compiler';
import * as import50 from '@angular/material/core/gestures/gesture-config';
import * as import51 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import52 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import53 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import54 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import55 from '@angular/core/src/animation/animation_queue';
import * as import56 from '@angular/core/src/linker/view_utils';
import * as import57 from '@angular/platform-browser/src/browser/title';
import * as import58 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import59 from '@angular/http/src/backends/browser_xhr';
import * as import60 from '@angular/http/src/base_response_options';
import * as import61 from '@angular/http/src/backends/xhr_backend';
import * as import62 from '@angular/http/src/base_request_options';
import * as import63 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import64 from '@angular/material/core/platform/platform';
import * as import65 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import66 from '@angular/material/core/overlay/overlay-container';
import * as import67 from '@angular/material/core/overlay/overlay';
import * as import68 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import69 from '@angular/material/core/a11y/interactivity-checker';
import * as import70 from '@angular/material/core/a11y/live-announcer';
import * as import71 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import72 from '@angular/material/dialog/dialog';
import * as import73 from '@angular/material/icon/icon-registry';
import * as import74 from '../services/weatherService';
import * as import75 from '../services/geolocation';
import * as import76 from '@angular/core/src/di/injector';
import * as import77 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import78 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import79 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import80 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import81 from './app.component.ngfactory';
import * as import82 from '@angular/core/src/i18n/tokens';
import * as import83 from '@angular/core/src/application_tokens';
import * as import84 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import85 from '@angular/platform-browser/src/dom/events/key_events';
import * as import86 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import87 from '@angular/core/src/zone/ng_zone';
import * as import88 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import89 from '@angular/core/src/console';
import * as import90 from '@angular/core/src/error_handler';
import * as import91 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import92 from '@angular/platform-browser/src/dom/animation_driver';
import * as import93 from '@angular/core/src/render/api';
import * as import94 from '@angular/core/src/security';
import * as import95 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import96 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import97 from '@angular/http/src/interfaces';
import * as import98 from '@angular/http/src/http';
import * as import99 from '../services/loggerService';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _DefaultStyleCompatibilityModeModule_3:import5.DefaultStyleCompatibilityModeModule;
  _MdRippleModule_4:import6.MdRippleModule;
  _MdButtonModule_5:import7.MdButtonModule;
  _MdCardModule_6:import8.MdCardModule;
  _MdChipsModule_7:import9.MdChipsModule;
  _MdCheckboxModule_8:import10.MdCheckboxModule;
  _MdLineModule_9:import11.MdLineModule;
  _MdGridListModule_10:import12.MdGridListModule;
  _InternalFormsSharedModule_11:import13.InternalFormsSharedModule;
  _FormsModule_12:import14.FormsModule;
  _PlatformModule_13:import15.PlatformModule;
  _MdInputModule_14:import16.MdInputModule;
  _MdListModule_15:import17.MdListModule;
  _MdProgressBarModule_16:import18.MdProgressBarModule;
  _MdProgressSpinnerModule_17:import19.MdProgressSpinnerModule;
  _PortalModule_18:import20.PortalModule;
  _OverlayModule_19:import21.OverlayModule;
  _MdSelectModule_20:import22.MdSelectModule;
  _A11yModule_21:import23.A11yModule;
  _MdSidenavModule_22:import24.MdSidenavModule;
  _ObserveContentModule_23:import25.ObserveContentModule;
  _MdTabsModule_24:import26.MdTabsModule;
  _MdToolbarModule_25:import27.MdToolbarModule;
  _ProjectionModule_26:import28.ProjectionModule;
  _RtlModule_27:import29.RtlModule;
  _MdButtonToggleModule_28:import30.MdButtonToggleModule;
  _MdDialogModule_29:import31.MdDialogModule;
  _HttpModule_30:import32.HttpModule;
  _MdIconModule_31:import33.MdIconModule;
  _MdMenuModule_32:import34.MdMenuModule;
  _MdRadioModule_33:import35.MdRadioModule;
  _MdSliderModule_34:import36.MdSliderModule;
  _MdSlideToggleModule_35:import37.MdSlideToggleModule;
  _MdSnackBarModule_36:import38.MdSnackBarModule;
  _MdTooltipModule_37:import39.MdTooltipModule;
  _MaterialRootModule_38:import40.MaterialRootModule;
  _MaterialModule_39:import40.MaterialModule;
  _CoreModule_40:import41.CoreModule;
  _SharedModule_41:import42.SharedModule;
  _WeatherListModule_42:import43.WeatherListModule;
  _MapModule_43:import44.MapModule;
  _AppModule_44:import1.AppModule;
  __LOCALE_ID_45:any;
  __NgLocalization_46:import45.NgLocaleLocalization;
  _ErrorHandler_47:any;
  _ApplicationInitStatus_48:import46.ApplicationInitStatus;
  _Testability_49:import47.Testability;
  _ApplicationRef__50:import48.ApplicationRef_;
  __ApplicationRef_51:any;
  __Compiler_52:import49.Compiler;
  __APP_ID_53:any;
  __DOCUMENT_54:any;
  __HAMMER_GESTURE_CONFIG_55:import50.GestureConfig;
  __EVENT_MANAGER_PLUGINS_56:any[];
  __EventManager_57:import51.EventManager;
  __DomSharedStylesHost_58:import52.DomSharedStylesHost;
  __AnimationDriver_59:any;
  __DomRootRenderer_60:import53.DomRootRenderer_;
  __RootRenderer_61:any;
  __DomSanitizer_62:import54.DomSanitizerImpl;
  __Sanitizer_63:any;
  __AnimationQueue_64:import55.AnimationQueue;
  __ViewUtils_65:import56.ViewUtils;
  __IterableDiffers_66:any;
  __KeyValueDiffers_67:any;
  __SharedStylesHost_68:any;
  __Title_69:import57.Title;
  __MATERIAL_COMPATIBILITY_MODE_70:any;
  __RadioControlRegistry_71:import58.RadioControlRegistry;
  __BrowserXhr_72:import59.BrowserXhr;
  __ResponseOptions_73:import60.BaseResponseOptions;
  __XSRFStrategy_74:any;
  __XHRBackend_75:import61.XHRBackend;
  __RequestOptions_76:import62.BaseRequestOptions;
  __Http_77:any;
  __ViewportRuler_78:import63.ViewportRuler;
  __Platform_79:import64.Platform;
  __OverlayPositionBuilder_80:import65.OverlayPositionBuilder;
  __OverlayContainer_81:import66.OverlayContainer;
  __Overlay_82:import67.Overlay;
  __ScrollDispatcher_83:import68.ScrollDispatcher;
  __InteractivityChecker_84:import69.InteractivityChecker;
  __DomProjection_85:import28.DomProjection;
  __LiveAnnouncer_86:import70.LiveAnnouncer;
  __UniqueSelectionDispatcher_87:import71.UniqueSelectionDispatcher;
  __MdDialog_88:import72.MdDialog;
  __MdIconRegistry_89:import73.MdIconRegistry;
  __MdSnackBar_90:import38.MdSnackBar;
  __WeatherService_91:import74.WeatherService;
  __LoggerService_92:any;
  __LocationService_93:import75.LocationService;
  constructor(parent:import76.Injector) {
    super(parent,[
      import77.MdDialogContainerNgFactory,
      import78.MdSnackBarContainerNgFactory,
      import79.SimpleSnackBarNgFactory,
      import80.TooltipComponentNgFactory,
      import81.AppComponentNgFactory
    ]
    ,[import81.AppComponentNgFactory]);
  }
  get _LOCALE_ID_45():any {
    if ((this.__LOCALE_ID_45 == null)) { (this.__LOCALE_ID_45 = import3._localeFactory(this.parent.get(import82.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_45;
  }
  get _NgLocalization_46():import45.NgLocaleLocalization {
    if ((this.__NgLocalization_46 == null)) { (this.__NgLocalization_46 = new import45.NgLocaleLocalization(this._LOCALE_ID_45)); }
    return this.__NgLocalization_46;
  }
  get _ApplicationRef_51():any {
    if ((this.__ApplicationRef_51 == null)) { (this.__ApplicationRef_51 = this._ApplicationRef__50); }
    return this.__ApplicationRef_51;
  }
  get _Compiler_52():import49.Compiler {
    if ((this.__Compiler_52 == null)) { (this.__Compiler_52 = new import49.Compiler()); }
    return this.__Compiler_52;
  }
  get _APP_ID_53():any {
    if ((this.__APP_ID_53 == null)) { (this.__APP_ID_53 = import83._appIdRandomProviderFactory()); }
    return this.__APP_ID_53;
  }
  get _DOCUMENT_54():any {
    if ((this.__DOCUMENT_54 == null)) { (this.__DOCUMENT_54 = import4._document()); }
    return this.__DOCUMENT_54;
  }
  get _HAMMER_GESTURE_CONFIG_55():import50.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_55 == null)) { (this.__HAMMER_GESTURE_CONFIG_55 = new import50.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_55;
  }
  get _EVENT_MANAGER_PLUGINS_56():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_56 == null)) { (this.__EVENT_MANAGER_PLUGINS_56 = [
      new import84.DomEventsPlugin(),
      new import85.KeyEventsPlugin(),
      new import86.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_55)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_56;
  }
  get _EventManager_57():import51.EventManager {
    if ((this.__EventManager_57 == null)) { (this.__EventManager_57 = new import51.EventManager(this._EVENT_MANAGER_PLUGINS_56,this.parent.get(import87.NgZone))); }
    return this.__EventManager_57;
  }
  get _DomSharedStylesHost_58():import52.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_58 == null)) { (this.__DomSharedStylesHost_58 = new import52.DomSharedStylesHost(this._DOCUMENT_54)); }
    return this.__DomSharedStylesHost_58;
  }
  get _AnimationDriver_59():any {
    if ((this.__AnimationDriver_59 == null)) { (this.__AnimationDriver_59 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_59;
  }
  get _DomRootRenderer_60():import53.DomRootRenderer_ {
    if ((this.__DomRootRenderer_60 == null)) { (this.__DomRootRenderer_60 = new import53.DomRootRenderer_(this._DOCUMENT_54,this._EventManager_57,this._DomSharedStylesHost_58,this._AnimationDriver_59,this._APP_ID_53)); }
    return this.__DomRootRenderer_60;
  }
  get _RootRenderer_61():any {
    if ((this.__RootRenderer_61 == null)) { (this.__RootRenderer_61 = import88._createConditionalRootRenderer(this._DomRootRenderer_60,this.parent.get(import88.NgProbeToken,(null as any)),this.parent.get(import48.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_61;
  }
  get _DomSanitizer_62():import54.DomSanitizerImpl {
    if ((this.__DomSanitizer_62 == null)) { (this.__DomSanitizer_62 = new import54.DomSanitizerImpl()); }
    return this.__DomSanitizer_62;
  }
  get _Sanitizer_63():any {
    if ((this.__Sanitizer_63 == null)) { (this.__Sanitizer_63 = this._DomSanitizer_62); }
    return this.__Sanitizer_63;
  }
  get _AnimationQueue_64():import55.AnimationQueue {
    if ((this.__AnimationQueue_64 == null)) { (this.__AnimationQueue_64 = new import55.AnimationQueue(this.parent.get(import87.NgZone))); }
    return this.__AnimationQueue_64;
  }
  get _ViewUtils_65():import56.ViewUtils {
    if ((this.__ViewUtils_65 == null)) { (this.__ViewUtils_65 = new import56.ViewUtils(this._RootRenderer_61,this._Sanitizer_63,this._AnimationQueue_64)); }
    return this.__ViewUtils_65;
  }
  get _IterableDiffers_66():any {
    if ((this.__IterableDiffers_66 == null)) { (this.__IterableDiffers_66 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_66;
  }
  get _KeyValueDiffers_67():any {
    if ((this.__KeyValueDiffers_67 == null)) { (this.__KeyValueDiffers_67 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_67;
  }
  get _SharedStylesHost_68():any {
    if ((this.__SharedStylesHost_68 == null)) { (this.__SharedStylesHost_68 = this._DomSharedStylesHost_58); }
    return this.__SharedStylesHost_68;
  }
  get _Title_69():import57.Title {
    if ((this.__Title_69 == null)) { (this.__Title_69 = new import57.Title()); }
    return this.__Title_69;
  }
  get _MATERIAL_COMPATIBILITY_MODE_70():any {
    if ((this.__MATERIAL_COMPATIBILITY_MODE_70 == null)) { (this.__MATERIAL_COMPATIBILITY_MODE_70 = false); }
    return this.__MATERIAL_COMPATIBILITY_MODE_70;
  }
  get _RadioControlRegistry_71():import58.RadioControlRegistry {
    if ((this.__RadioControlRegistry_71 == null)) { (this.__RadioControlRegistry_71 = new import58.RadioControlRegistry()); }
    return this.__RadioControlRegistry_71;
  }
  get _BrowserXhr_72():import59.BrowserXhr {
    if ((this.__BrowserXhr_72 == null)) { (this.__BrowserXhr_72 = new import59.BrowserXhr()); }
    return this.__BrowserXhr_72;
  }
  get _ResponseOptions_73():import60.BaseResponseOptions {
    if ((this.__ResponseOptions_73 == null)) { (this.__ResponseOptions_73 = new import60.BaseResponseOptions()); }
    return this.__ResponseOptions_73;
  }
  get _XSRFStrategy_74():any {
    if ((this.__XSRFStrategy_74 == null)) { (this.__XSRFStrategy_74 = import32._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_74;
  }
  get _XHRBackend_75():import61.XHRBackend {
    if ((this.__XHRBackend_75 == null)) { (this.__XHRBackend_75 = new import61.XHRBackend(this._BrowserXhr_72,this._ResponseOptions_73,this._XSRFStrategy_74)); }
    return this.__XHRBackend_75;
  }
  get _RequestOptions_76():import62.BaseRequestOptions {
    if ((this.__RequestOptions_76 == null)) { (this.__RequestOptions_76 = new import62.BaseRequestOptions()); }
    return this.__RequestOptions_76;
  }
  get _Http_77():any {
    if ((this.__Http_77 == null)) { (this.__Http_77 = import32.httpFactory(this._XHRBackend_75,this._RequestOptions_76)); }
    return this.__Http_77;
  }
  get _ViewportRuler_78():import63.ViewportRuler {
    if ((this.__ViewportRuler_78 == null)) { (this.__ViewportRuler_78 = new import63.ViewportRuler()); }
    return this.__ViewportRuler_78;
  }
  get _Platform_79():import64.Platform {
    if ((this.__Platform_79 == null)) { (this.__Platform_79 = new import64.Platform()); }
    return this.__Platform_79;
  }
  get _OverlayPositionBuilder_80():import65.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_80 == null)) { (this.__OverlayPositionBuilder_80 = new import65.OverlayPositionBuilder(this._ViewportRuler_78)); }
    return this.__OverlayPositionBuilder_80;
  }
  get _OverlayContainer_81():import66.OverlayContainer {
    if ((this.__OverlayContainer_81 == null)) { (this.__OverlayContainer_81 = new import66.OverlayContainer()); }
    return this.__OverlayContainer_81;
  }
  get _Overlay_82():import67.Overlay {
    if ((this.__Overlay_82 == null)) { (this.__Overlay_82 = new import67.Overlay(this._OverlayContainer_81,this,this._OverlayPositionBuilder_80,this._ApplicationRef_51,this,this.parent.get(import87.NgZone))); }
    return this.__Overlay_82;
  }
  get _ScrollDispatcher_83():import68.ScrollDispatcher {
    if ((this.__ScrollDispatcher_83 == null)) { (this.__ScrollDispatcher_83 = new import68.ScrollDispatcher()); }
    return this.__ScrollDispatcher_83;
  }
  get _InteractivityChecker_84():import69.InteractivityChecker {
    if ((this.__InteractivityChecker_84 == null)) { (this.__InteractivityChecker_84 = new import69.InteractivityChecker(this._Platform_79)); }
    return this.__InteractivityChecker_84;
  }
  get _DomProjection_85():import28.DomProjection {
    if ((this.__DomProjection_85 == null)) { (this.__DomProjection_85 = new import28.DomProjection()); }
    return this.__DomProjection_85;
  }
  get _LiveAnnouncer_86():import70.LiveAnnouncer {
    if ((this.__LiveAnnouncer_86 == null)) { (this.__LiveAnnouncer_86 = new import70.LiveAnnouncer(this.parent.get(import70.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_86;
  }
  get _UniqueSelectionDispatcher_87():import71.UniqueSelectionDispatcher {
    if ((this.__UniqueSelectionDispatcher_87 == null)) { (this.__UniqueSelectionDispatcher_87 = new import71.UniqueSelectionDispatcher()); }
    return this.__UniqueSelectionDispatcher_87;
  }
  get _MdDialog_88():import72.MdDialog {
    if ((this.__MdDialog_88 == null)) { (this.__MdDialog_88 = new import72.MdDialog(this._Overlay_82,this)); }
    return this.__MdDialog_88;
  }
  get _MdIconRegistry_89():import73.MdIconRegistry {
    if ((this.__MdIconRegistry_89 == null)) { (this.__MdIconRegistry_89 = new import73.MdIconRegistry(this._Http_77,this._DomSanitizer_62)); }
    return this.__MdIconRegistry_89;
  }
  get _MdSnackBar_90():import38.MdSnackBar {
    if ((this.__MdSnackBar_90 == null)) { (this.__MdSnackBar_90 = new import38.MdSnackBar(this._Overlay_82,this._LiveAnnouncer_86)); }
    return this.__MdSnackBar_90;
  }
  get _WeatherService_91():import74.WeatherService {
    if ((this.__WeatherService_91 == null)) { (this.__WeatherService_91 = new import74.WeatherService()); }
    return this.__WeatherService_91;
  }
  get _LoggerService_92():any {
    if ((this.__LoggerService_92 == null)) { (this.__LoggerService_92 = import42.loggerFactory()); }
    return this.__LoggerService_92;
  }
  get _LocationService_93():import75.LocationService {
    if ((this.__LocationService_93 == null)) { (this.__LocationService_93 = new import75.LocationService()); }
    return this.__LocationService_93;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._DefaultStyleCompatibilityModeModule_3 = new import5.DefaultStyleCompatibilityModeModule();
    this._MdRippleModule_4 = new import6.MdRippleModule();
    this._MdButtonModule_5 = new import7.MdButtonModule();
    this._MdCardModule_6 = new import8.MdCardModule();
    this._MdChipsModule_7 = new import9.MdChipsModule();
    this._MdCheckboxModule_8 = new import10.MdCheckboxModule();
    this._MdLineModule_9 = new import11.MdLineModule();
    this._MdGridListModule_10 = new import12.MdGridListModule();
    this._InternalFormsSharedModule_11 = new import13.InternalFormsSharedModule();
    this._FormsModule_12 = new import14.FormsModule();
    this._PlatformModule_13 = new import15.PlatformModule();
    this._MdInputModule_14 = new import16.MdInputModule();
    this._MdListModule_15 = new import17.MdListModule();
    this._MdProgressBarModule_16 = new import18.MdProgressBarModule();
    this._MdProgressSpinnerModule_17 = new import19.MdProgressSpinnerModule();
    this._PortalModule_18 = new import20.PortalModule();
    this._OverlayModule_19 = new import21.OverlayModule();
    this._MdSelectModule_20 = new import22.MdSelectModule();
    this._A11yModule_21 = new import23.A11yModule();
    this._MdSidenavModule_22 = new import24.MdSidenavModule();
    this._ObserveContentModule_23 = new import25.ObserveContentModule();
    this._MdTabsModule_24 = new import26.MdTabsModule();
    this._MdToolbarModule_25 = new import27.MdToolbarModule();
    this._ProjectionModule_26 = new import28.ProjectionModule();
    this._RtlModule_27 = new import29.RtlModule();
    this._MdButtonToggleModule_28 = new import30.MdButtonToggleModule();
    this._MdDialogModule_29 = new import31.MdDialogModule();
    this._HttpModule_30 = new import32.HttpModule();
    this._MdIconModule_31 = new import33.MdIconModule();
    this._MdMenuModule_32 = new import34.MdMenuModule();
    this._MdRadioModule_33 = new import35.MdRadioModule();
    this._MdSliderModule_34 = new import36.MdSliderModule();
    this._MdSlideToggleModule_35 = new import37.MdSlideToggleModule();
    this._MdSnackBarModule_36 = new import38.MdSnackBarModule();
    this._MdTooltipModule_37 = new import39.MdTooltipModule();
    this._MaterialRootModule_38 = new import40.MaterialRootModule();
    this._MaterialModule_39 = new import40.MaterialModule();
    this._CoreModule_40 = new import41.CoreModule();
    this._SharedModule_41 = new import42.SharedModule();
    this._WeatherListModule_42 = new import43.WeatherListModule();
    this._MapModule_43 = new import44.MapModule();
    this._AppModule_44 = new import1.AppModule();
    this._ErrorHandler_47 = import4.errorHandler();
    this._ApplicationInitStatus_48 = new import46.ApplicationInitStatus(this.parent.get(import46.APP_INITIALIZER,(null as any)));
    this._Testability_49 = new import47.Testability(this.parent.get(import87.NgZone));
    this._ApplicationRef__50 = new import48.ApplicationRef_(this.parent.get(import87.NgZone),this.parent.get(import89.Console),this,this._ErrorHandler_47,this,this._ApplicationInitStatus_48,this.parent.get(import47.TestabilityRegistry,(null as any)),this._Testability_49);
    return this._AppModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.DefaultStyleCompatibilityModeModule)) { return this._DefaultStyleCompatibilityModeModule_3; }
    if ((token === import6.MdRippleModule)) { return this._MdRippleModule_4; }
    if ((token === import7.MdButtonModule)) { return this._MdButtonModule_5; }
    if ((token === import8.MdCardModule)) { return this._MdCardModule_6; }
    if ((token === import9.MdChipsModule)) { return this._MdChipsModule_7; }
    if ((token === import10.MdCheckboxModule)) { return this._MdCheckboxModule_8; }
    if ((token === import11.MdLineModule)) { return this._MdLineModule_9; }
    if ((token === import12.MdGridListModule)) { return this._MdGridListModule_10; }
    if ((token === import13.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_11; }
    if ((token === import14.FormsModule)) { return this._FormsModule_12; }
    if ((token === import15.PlatformModule)) { return this._PlatformModule_13; }
    if ((token === import16.MdInputModule)) { return this._MdInputModule_14; }
    if ((token === import17.MdListModule)) { return this._MdListModule_15; }
    if ((token === import18.MdProgressBarModule)) { return this._MdProgressBarModule_16; }
    if ((token === import19.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_17; }
    if ((token === import20.PortalModule)) { return this._PortalModule_18; }
    if ((token === import21.OverlayModule)) { return this._OverlayModule_19; }
    if ((token === import22.MdSelectModule)) { return this._MdSelectModule_20; }
    if ((token === import23.A11yModule)) { return this._A11yModule_21; }
    if ((token === import24.MdSidenavModule)) { return this._MdSidenavModule_22; }
    if ((token === import25.ObserveContentModule)) { return this._ObserveContentModule_23; }
    if ((token === import26.MdTabsModule)) { return this._MdTabsModule_24; }
    if ((token === import27.MdToolbarModule)) { return this._MdToolbarModule_25; }
    if ((token === import28.ProjectionModule)) { return this._ProjectionModule_26; }
    if ((token === import29.RtlModule)) { return this._RtlModule_27; }
    if ((token === import30.MdButtonToggleModule)) { return this._MdButtonToggleModule_28; }
    if ((token === import31.MdDialogModule)) { return this._MdDialogModule_29; }
    if ((token === import32.HttpModule)) { return this._HttpModule_30; }
    if ((token === import33.MdIconModule)) { return this._MdIconModule_31; }
    if ((token === import34.MdMenuModule)) { return this._MdMenuModule_32; }
    if ((token === import35.MdRadioModule)) { return this._MdRadioModule_33; }
    if ((token === import36.MdSliderModule)) { return this._MdSliderModule_34; }
    if ((token === import37.MdSlideToggleModule)) { return this._MdSlideToggleModule_35; }
    if ((token === import38.MdSnackBarModule)) { return this._MdSnackBarModule_36; }
    if ((token === import39.MdTooltipModule)) { return this._MdTooltipModule_37; }
    if ((token === import40.MaterialRootModule)) { return this._MaterialRootModule_38; }
    if ((token === import40.MaterialModule)) { return this._MaterialModule_39; }
    if ((token === import41.CoreModule)) { return this._CoreModule_40; }
    if ((token === import42.SharedModule)) { return this._SharedModule_41; }
    if ((token === import43.WeatherListModule)) { return this._WeatherListModule_42; }
    if ((token === import44.MapModule)) { return this._MapModule_43; }
    if ((token === import1.AppModule)) { return this._AppModule_44; }
    if ((token === import82.LOCALE_ID)) { return this._LOCALE_ID_45; }
    if ((token === import45.NgLocalization)) { return this._NgLocalization_46; }
    if ((token === import90.ErrorHandler)) { return this._ErrorHandler_47; }
    if ((token === import46.ApplicationInitStatus)) { return this._ApplicationInitStatus_48; }
    if ((token === import47.Testability)) { return this._Testability_49; }
    if ((token === import48.ApplicationRef_)) { return this._ApplicationRef__50; }
    if ((token === import48.ApplicationRef)) { return this._ApplicationRef_51; }
    if ((token === import49.Compiler)) { return this._Compiler_52; }
    if ((token === import83.APP_ID)) { return this._APP_ID_53; }
    if ((token === import91.DOCUMENT)) { return this._DOCUMENT_54; }
    if ((token === import86.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_55; }
    if ((token === import51.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_56; }
    if ((token === import51.EventManager)) { return this._EventManager_57; }
    if ((token === import52.DomSharedStylesHost)) { return this._DomSharedStylesHost_58; }
    if ((token === import92.AnimationDriver)) { return this._AnimationDriver_59; }
    if ((token === import53.DomRootRenderer)) { return this._DomRootRenderer_60; }
    if ((token === import93.RootRenderer)) { return this._RootRenderer_61; }
    if ((token === import54.DomSanitizer)) { return this._DomSanitizer_62; }
    if ((token === import94.Sanitizer)) { return this._Sanitizer_63; }
    if ((token === import55.AnimationQueue)) { return this._AnimationQueue_64; }
    if ((token === import56.ViewUtils)) { return this._ViewUtils_65; }
    if ((token === import95.IterableDiffers)) { return this._IterableDiffers_66; }
    if ((token === import96.KeyValueDiffers)) { return this._KeyValueDiffers_67; }
    if ((token === import52.SharedStylesHost)) { return this._SharedStylesHost_68; }
    if ((token === import57.Title)) { return this._Title_69; }
    if ((token === import5.MATERIAL_COMPATIBILITY_MODE)) { return this._MATERIAL_COMPATIBILITY_MODE_70; }
    if ((token === import58.RadioControlRegistry)) { return this._RadioControlRegistry_71; }
    if ((token === import59.BrowserXhr)) { return this._BrowserXhr_72; }
    if ((token === import60.ResponseOptions)) { return this._ResponseOptions_73; }
    if ((token === import97.XSRFStrategy)) { return this._XSRFStrategy_74; }
    if ((token === import61.XHRBackend)) { return this._XHRBackend_75; }
    if ((token === import62.RequestOptions)) { return this._RequestOptions_76; }
    if ((token === import98.Http)) { return this._Http_77; }
    if ((token === import63.ViewportRuler)) { return this._ViewportRuler_78; }
    if ((token === import64.Platform)) { return this._Platform_79; }
    if ((token === import65.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_80; }
    if ((token === import66.OverlayContainer)) { return this._OverlayContainer_81; }
    if ((token === import67.Overlay)) { return this._Overlay_82; }
    if ((token === import68.ScrollDispatcher)) { return this._ScrollDispatcher_83; }
    if ((token === import69.InteractivityChecker)) { return this._InteractivityChecker_84; }
    if ((token === import28.DomProjection)) { return this._DomProjection_85; }
    if ((token === import70.LiveAnnouncer)) { return this._LiveAnnouncer_86; }
    if ((token === import71.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_87; }
    if ((token === import72.MdDialog)) { return this._MdDialog_88; }
    if ((token === import73.MdIconRegistry)) { return this._MdIconRegistry_89; }
    if ((token === import38.MdSnackBar)) { return this._MdSnackBar_90; }
    if ((token === import74.WeatherService)) { return this._WeatherService_91; }
    if ((token === import99.LoggerService)) { return this._LoggerService_92; }
    if ((token === import75.LocationService)) { return this._LocationService_93; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__50.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);