/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './list.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './list.css.shim.ngstyle';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../../directives/temperatureColor.ngfactory';
import * as import12 from '../../../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import13 from '../../../directives/rotateWind.ngfactory';
import * as import14 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '@angular/material/button/button';
import * as import16 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '../../../directives/temperatureColor';
import * as import20 from '@angular/common/src/directives/ng_switch';
import * as import21 from '../../../directives/rotateWind';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/common/src/directives/ng_for';
import * as import26 from '../../../pipes/kelvinToCelsius';
import * as import27 from '@angular/common/src/pipes/number_pipe';
import * as import28 from '@angular/core/src/i18n/tokens';
export class Wrapper_ListComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ListComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  constructor() {
    this._changed = false;
    this.context = new import0.ListComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
  }
  check_list(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.list = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.setFavorite.subscribe(_eventHandler.bind(view,'setFavorite'))); }
    if (emit1) { (this.subscription1 = this.context.unsetFavorite.subscribe(_eventHandler.bind(view,'unsetFavorite'))); }
    if (emit2) { (this.subscription2 = this.context.deleteItem.subscribe(_eventHandler.bind(view,'deleteItem'))); }
  }
}
var renderType_ListComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ListComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ListComponent>;
  _ListComponent_0_3:Wrapper_ListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ListComponent_Host0,renderType_ListComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'list-table',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ListComponent0(this.viewUtils,this,0,this._el_0);
    this._ListComponent_0_3 = new Wrapper_ListComponent();
    this.compView_0.create(this._ListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ListComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ListComponent) && (0 === requestNodeIndex))) { return this._ListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._ListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ListComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ListComponentNgFactory:import8.ComponentFactory<import0.ListComponent> = new import8.ComponentFactory<import0.ListComponent>('list-table',View_ListComponent_Host0,import0.ListComponent);
const styles_ListComponent:any[] = [import9.styles];
class View_ListComponent3 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent3,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-snowflake-o'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent4 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent4,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-cloud'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent5 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent5,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-tint'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent6 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent6,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-eye-slash'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent7 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent7,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-eye-slash'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent8 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent8,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-sun-o'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ListComponent9 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent9,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-star'),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.unsetFavorite.emit(this.parentView.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ListComponent10 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent10,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-star-empty'),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.setFavorite.emit(this.parentView.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ListComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _TemperatureColor_7_3:import11.Wrapper_TemperatureColor;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _NgSwitch_15_3:import12.Wrapper_NgSwitch;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import10.ViewContainer;
  _TemplateRef_17_5:any;
  _NgSwitchCase_17_6:import12.Wrapper_NgSwitchCase;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _vc_19:import10.ViewContainer;
  _TemplateRef_19_5:any;
  _NgSwitchCase_19_6:import12.Wrapper_NgSwitchCase;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import10.ViewContainer;
  _TemplateRef_21_5:any;
  _NgSwitchCase_21_6:import12.Wrapper_NgSwitchCase;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import10.ViewContainer;
  _TemplateRef_23_5:any;
  _NgSwitchCase_23_6:import12.Wrapper_NgSwitchCase;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import10.ViewContainer;
  _TemplateRef_25_5:any;
  _NgSwitchCase_25_6:import12.Wrapper_NgSwitchCase;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import10.ViewContainer;
  _TemplateRef_27_5:any;
  _NgSwitchCase_27_6:import12.Wrapper_NgSwitchCase;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _el_38:any;
  _RotateWind_38_3:import13.Wrapper_RotateWind;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _vc_46:import10.ViewContainer;
  _TemplateRef_46_5:any;
  _NgIf_46_6:import14.Wrapper_NgIf;
  _text_47:any;
  _anchor_48:any;
  /*private*/ _vc_48:import10.ViewContainer;
  _TemplateRef_48_5:any;
  _NgIf_48_6:import14.Wrapper_NgIf;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  compView_52:import2.AppView<import15.MdButton>;
  _MdButton_52_3:import16.Wrapper_MdButton;
  _text_53:any;
  _text_54:any;
  /*private*/ _expr_84:any;
  _pipe_sgKelvinToCelsiusPipe_0_0:any;
  /*private*/ _expr_86:any;
  _pipe_sgKelvinToCelsiusPipe_0_1:any;
  _pipe_number_1_0:any;
  _pipe_sgKelvinToCelsiusPipe_0_2:any;
  _pipe_number_1_1:any;
  /*private*/ _expr_91:any;
  /*private*/ _expr_92:any;
  /*private*/ _expr_93:any;
  /*private*/ _expr_94:any;
  _pipe_number_1_2:any;
  /*private*/ _expr_96:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent2,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_84 = import1.UNINITIALIZED;
    this._expr_86 = import1.UNINITIALIZED;
    this._expr_91 = import1.UNINITIALIZED;
    this._expr_92 = import1.UNINITIALIZED;
    this._expr_93 = import1.UNINITIALIZED;
    this._expr_94 = import1.UNINITIALIZED;
    this._expr_96 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','temp-cell'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','temp-background'),(null as any));
    this._TemperatureColor_7_3 = new import11.Wrapper_TemperatureColor(new import17.ElementRef(this._el_7));
    this._text_8 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_5,'span',new import3.InlineArray2(2,'class','temp-numbers'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_15_3 = new import12.Wrapper_NgSwitch();
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_17 = new import10.ViewContainer(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import18.TemplateRef_(this,17,this._anchor_17);
    this._NgSwitchCase_17_6 = new import12.Wrapper_NgSwitchCase(this._vc_17.vcRef,this._TemplateRef_17_5,this._NgSwitch_15_3.context);
    this._text_18 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_19 = new import10.ViewContainer(19,15,this,this._anchor_19);
    this._TemplateRef_19_5 = new import18.TemplateRef_(this,19,this._anchor_19);
    this._NgSwitchCase_19_6 = new import12.Wrapper_NgSwitchCase(this._vc_19.vcRef,this._TemplateRef_19_5,this._NgSwitch_15_3.context);
    this._text_20 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_21 = new import10.ViewContainer(21,15,this,this._anchor_21);
    this._TemplateRef_21_5 = new import18.TemplateRef_(this,21,this._anchor_21);
    this._NgSwitchCase_21_6 = new import12.Wrapper_NgSwitchCase(this._vc_21.vcRef,this._TemplateRef_21_5,this._NgSwitch_15_3.context);
    this._text_22 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_23 = new import10.ViewContainer(23,15,this,this._anchor_23);
    this._TemplateRef_23_5 = new import18.TemplateRef_(this,23,this._anchor_23);
    this._NgSwitchCase_23_6 = new import12.Wrapper_NgSwitchCase(this._vc_23.vcRef,this._TemplateRef_23_5,this._NgSwitch_15_3.context);
    this._text_24 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_25 = new import10.ViewContainer(25,15,this,this._anchor_25);
    this._TemplateRef_25_5 = new import18.TemplateRef_(this,25,this._anchor_25);
    this._NgSwitchCase_25_6 = new import12.Wrapper_NgSwitchCase(this._vc_25.vcRef,this._TemplateRef_25_5,this._NgSwitch_15_3.context);
    this._text_26 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_27 = new import10.ViewContainer(27,15,this,this._anchor_27);
    this._TemplateRef_27_5 = new import18.TemplateRef_(this,27,this._anchor_27);
    this._NgSwitchCase_27_6 = new import12.Wrapper_NgSwitchCase(this._vc_27.vcRef,this._TemplateRef_27_5,this._NgSwitch_15_3.context);
    this._text_28 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._text_29 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_37,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-arrow-up'),(null as any));
    this._RotateWind_38_3 = new import13.Wrapper_RotateWind(new import17.ElementRef(this._el_38));
    this._text_39 = this.renderer.createText(this._el_37,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_44,(null as any));
    this._vc_46 = new import10.ViewContainer(46,44,this,this._anchor_46);
    this._TemplateRef_46_5 = new import18.TemplateRef_(this,46,this._anchor_46);
    this._NgIf_46_6 = new import14.Wrapper_NgIf(this._vc_46.vcRef,this._TemplateRef_46_5);
    this._text_47 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._anchor_48 = this.renderer.createTemplateAnchor(this._el_44,(null as any));
    this._vc_48 = new import10.ViewContainer(48,44,this,this._anchor_48);
    this._TemplateRef_48_5 = new import18.TemplateRef_(this,48,this._anchor_48);
    this._NgIf_48_6 = new import14.Wrapper_NgIf(this._vc_48.vcRef,this._TemplateRef_48_5);
    this._text_49 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_51,'button',new import3.InlineArray4(4,'class','btn btn-default','md-raised-button',''),(null as any));
    this.compView_52 = new import16.View_MdButton0(this.viewUtils,this,52,this._el_52);
    this._MdButton_52_3 = new import16.Wrapper_MdButton(new import17.ElementRef(this._el_52),this.renderer);
    this._text_53 = this.renderer.createText((null as any),'Delete',(null as any));
    this.compView_52.create(this._MdButton_52_3.context);
    this._text_54 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._pipe_sgKelvinToCelsiusPipe_0_0 = import3.pureProxy1((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0));
    this._pipe_sgKelvinToCelsiusPipe_0_1 = import3.pureProxy1((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0));
    this._pipe_number_1_0 = import3.pureProxy2((<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_number_1));
    this._pipe_sgKelvinToCelsiusPipe_0_2 = import3.pureProxy1((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0));
    this._pipe_number_1_1 = import3.pureProxy2((<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_number_1));
    this._pipe_number_1_2 = import3.pureProxy2((<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_ListComponent0>this.parentView.parentView)._pipe_number_1));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_52));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._anchor_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._text_53,
      this._text_54
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemperatureColor) && (7 === requestNodeIndex))) { return this._TemperatureColor_7_3.context; }
    if (((token === import18.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import20.NgSwitchCase) && (17 === requestNodeIndex))) { return this._NgSwitchCase_17_6.context; }
    if (((token === import18.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import20.NgSwitchCase) && (19 === requestNodeIndex))) { return this._NgSwitchCase_19_6.context; }
    if (((token === import18.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import20.NgSwitchCase) && (21 === requestNodeIndex))) { return this._NgSwitchCase_21_6.context; }
    if (((token === import18.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import20.NgSwitchCase) && (23 === requestNodeIndex))) { return this._NgSwitchCase_23_6.context; }
    if (((token === import18.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import20.NgSwitchCase) && (25 === requestNodeIndex))) { return this._NgSwitchCase_25_6.context; }
    if (((token === import18.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import20.NgSwitchCase) && (27 === requestNodeIndex))) { return this._NgSwitchCase_27_6.context; }
    if (((token === import20.NgSwitch) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgSwitch_15_3.context; }
    if (((token === import21.RotateWind) && (38 === requestNodeIndex))) { return this._RotateWind_38_3.context; }
    if (((token === import18.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import22.NgIf) && (46 === requestNodeIndex))) { return this._NgIf_46_6.context; }
    if (((token === import18.TemplateRef) && (48 === requestNodeIndex))) { return this._TemplateRef_48_5; }
    if (((token === import22.NgIf) && (48 === requestNodeIndex))) { return this._NgIf_48_6.context; }
    if (((token === import15.MdButton) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._MdButton_52_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_7_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_sgKelvinToCelsiusPipe_0_0,(<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform)(this.context.$implicit.main.temp));
    this._TemperatureColor_7_3.check_temperature(currVal_7_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._TemperatureColor_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_15_0_0:any = this.context.$implicit.weather[0].main;
    this._NgSwitch_15_3.check_ngSwitch(currVal_15_0_0,throwOnChange,false);
    this._NgSwitch_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_17_0_0:any = 'Snow';
    this._NgSwitchCase_17_6.check_ngSwitchCase(currVal_17_0_0,throwOnChange,false);
    this._NgSwitchCase_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    const currVal_19_0_0:any = 'Clouds';
    this._NgSwitchCase_19_6.check_ngSwitchCase(currVal_19_0_0,throwOnChange,false);
    this._NgSwitchCase_19_6.ngDoCheck(this,this._anchor_19,throwOnChange);
    const currVal_21_0_0:any = 'Rain';
    this._NgSwitchCase_21_6.check_ngSwitchCase(currVal_21_0_0,throwOnChange,false);
    this._NgSwitchCase_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    const currVal_23_0_0:any = 'Mist';
    this._NgSwitchCase_23_6.check_ngSwitchCase(currVal_23_0_0,throwOnChange,false);
    this._NgSwitchCase_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    const currVal_25_0_0:any = 'Fog';
    this._NgSwitchCase_25_6.check_ngSwitchCase(currVal_25_0_0,throwOnChange,false);
    this._NgSwitchCase_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    const currVal_27_0_0:any = 'Clear';
    this._NgSwitchCase_27_6.check_ngSwitchCase(currVal_27_0_0,throwOnChange,false);
    this._NgSwitchCase_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    const currVal_38_0_0:any = this.context.$implicit.wind.deg;
    this._RotateWind_38_3.check_angle(currVal_38_0_0,throwOnChange,false);
    this._RotateWind_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_46_0_0:any = this.context.$implicit.favorite;
    this._NgIf_46_6.check_ngIf(currVal_46_0_0,throwOnChange,false);
    this._NgIf_46_6.ngDoCheck(this,this._anchor_46,throwOnChange);
    const currVal_48_0_0:boolean = !this.context.$implicit.favorite;
    this._NgIf_48_6.check_ngIf(currVal_48_0_0,throwOnChange,false);
    this._NgIf_48_6.ngDoCheck(this,this._anchor_48,throwOnChange);
    const currVal_52_0_0:any = this.context.$implicit.favorite;
    this._MdButton_52_3.check_disabled(currVal_52_0_0,throwOnChange,false);
    if (this._MdButton_52_3.ngDoCheck(this,this._el_52,throwOnChange)) { this.compView_52.markAsCheckOnce(); }
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    this._vc_19.detectChangesInNestedViews(throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    this._vc_46.detectChangesInNestedViews(throwOnChange);
    this._vc_48.detectChangesInNestedViews(throwOnChange);
    const currVal_84:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setText(this._text_3,currVal_84);
      this._expr_84 = currVal_84;
    }
    valUnwrapper.reset();
    const currVal_86:any = import3.inlineInterpolate(2,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_0,(<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform)(valUnwrapper.unwrap(import3.castByValue(this._pipe_sgKelvinToCelsiusPipe_0_1,(<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform)(this.context.$implicit.main.temp_min)),'1.1-1')),' - ',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_1,(<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform)(valUnwrapper.unwrap(import3.castByValue(this._pipe_sgKelvinToCelsiusPipe_0_2,(<View_ListComponent0>this.parentView.parentView)._pipe_sgKelvinToCelsiusPipe_0.transform)(this.context.$implicit.main.temp_max)),'1.1-1')),'°C');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_86,currVal_86))) {
      this.renderer.setText(this._text_10,currVal_86);
      this._expr_86 = currVal_86;
    }
    const currVal_91:any = import3.inlineInterpolate(1,'\n                   ',this.context.$implicit.weather[0].main,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_91,currVal_91)) {
      this.renderer.setText(this._text_29,currVal_91);
      this._expr_91 = currVal_91;
    }
    const currVal_92:any = import3.inlineInterpolate(1,'',this.context.$implicit.main.humidity,'%');
    if (import3.checkBinding(throwOnChange,this._expr_92,currVal_92)) {
      this.renderer.setText(this._text_32,currVal_92);
      this._expr_92 = currVal_92;
    }
    const currVal_93:any = import3.inlineInterpolate(1,'',this.context.$implicit.main.pressure,' hPa');
    if (import3.checkBinding(throwOnChange,this._expr_93,currVal_93)) {
      this.renderer.setText(this._text_35,currVal_93);
      this._expr_93 = currVal_93;
    }
    valUnwrapper.reset();
    const currVal_94:any = import3.inlineInterpolate(1,'   ',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_2,(<View_ListComponent0>this.parentView.parentView)._pipe_number_1.transform)(this.context.$implicit.wind.speed,'1.1-1')),'m/s');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_94,currVal_94))) {
      this.renderer.setText(this._text_39,currVal_94);
      this._expr_94 = currVal_94;
    }
    const currVal_96:any = import3.inlineInterpolate(1,'',this.context.$implicit.clouds.all,'%');
    if (import3.checkBinding(throwOnChange,this._expr_96,currVal_96)) {
      this.renderer.setText(this._text_42,currVal_96);
      this._expr_96 = currVal_96;
    }
    this._MdButton_52_3.checkHost(this,this.compView_52,this._el_52,throwOnChange);
    this.compView_52.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_17.destroyNestedViews();
    this._vc_19.destroyNestedViews();
    this._vc_21.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._vc_27.destroyNestedViews();
    this._vc_46.destroyNestedViews();
    this._vc_48.destroyNestedViews();
    this.compView_52.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 52) && (ngContentIndex == 0))) { cb(this._text_53,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 17)) { return new View_ListComponent3(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    if ((nodeIndex == 19)) { return new View_ListComponent4(this.viewUtils,this,19,this._anchor_19,this._vc_19); }
    if ((nodeIndex == 21)) { return new View_ListComponent5(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    if ((nodeIndex == 23)) { return new View_ListComponent6(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 25)) { return new View_ListComponent7(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    if ((nodeIndex == 27)) { return new View_ListComponent8(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    if ((nodeIndex == 46)) { return new View_ListComponent9(this.viewUtils,this,46,this._anchor_46,this._vc_46); }
    if ((nodeIndex == 48)) { return new View_ListComponent10(this.viewUtils,this,48,this._anchor_48,this._vc_48); }
    return (null as any);
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.compView_52.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_52_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.deleteItem.emit(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ListComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import10.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import23.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ListComponent1,renderType_ListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import10.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import23.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import24.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import25.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.list;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ListComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
var renderType_ListComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_ListComponent,{});
export class View_ListComponent0 extends import2.AppView<import0.ListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import10.ViewContainer;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import14.Wrapper_NgIf;
  _text_36:any;
  _pipe_sgKelvinToCelsiusPipe_0:import26.KelvinToCelsiusPipe;
  _pipe_number_1:import27.DecimalPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ListComponent0,renderType_ListComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'table',new import3.InlineArray2(2,'class','table'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'City name',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Temperature',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Weather',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Humidity',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Pressure',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Wind',(null as any));
    this._text_23 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Clouds',(null as any));
    this._text_26 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Favorite',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_4,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Delete city',(null as any));
    this._text_32 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_35 = new import10.ViewContainer(35,0,this,this._anchor_35);
    this._TemplateRef_35_5 = new import18.TemplateRef_(this,35,this._anchor_35);
    this._NgIf_35_6 = new import14.Wrapper_NgIf(this._vc_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_sgKelvinToCelsiusPipe_0 = new import26.KelvinToCelsiusPipe();
    this._pipe_number_1 = new import27.DecimalPipe(this.parentView.injectorGet(import28.LOCALE_ID,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._anchor_35,
      this._text_36
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import22.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_35_0_0:any = this.context.list;
    this._NgIf_35_6.check_ngIf(currVal_35_0_0,throwOnChange,false);
    this._NgIf_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_35.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 35)) { return new View_ListComponent1(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    return (null as any);
  }
}