/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.temp-cell[_ngcontent-%COMP%] {\r\n    position: relative;\r\n}\r\n\r\n.temp-background[_ngcontent-%COMP%] {\r\n    position: absolute;\r\n    width: 100%;\r\n    height: 100%;\r\n    top: 0;\r\n    left: 0;\r\n    opacity: 0.7;\r\n}\r\n\r\n.temp-numbers[_ngcontent-%COMP%] {\r\n    position: absolute;\r\n}'];