/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './footer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './footer.css.shim.ngstyle';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/material/toolbar/toolbar';
import * as import11 from '../../../../node_modules/@angular/material/toolbar/toolbar.ngfactory';
import * as import12 from '../../../directives/customIf.ngfactory';
import * as import13 from '@angular/common/src/pipes/date_pipe';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/i18n/tokens';
import * as import18 from '../../../directives/customIf';
export class Wrapper_FooterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FooterComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FooterComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FooterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FooterComponent>;
  _FooterComponent_0_3:Wrapper_FooterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent_Host0,renderType_FooterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-footer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FooterComponent0(this.viewUtils,this,0,this._el_0);
    this._FooterComponent_0_3 = new Wrapper_FooterComponent();
    this.compView_0.create(this._FooterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FooterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._FooterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FooterComponentNgFactory:import7.ComponentFactory<import0.FooterComponent> = new import7.ComponentFactory<import0.FooterComponent>('app-footer',View_FooterComponent_Host0,import0.FooterComponent);
const styles_FooterComponent:any[] = [import8.styles];
class View_FooterComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_FooterComponent1,renderType_FooterComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'   Merry Christmas!!!',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_FooterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_FooterComponent,{});
export class View_FooterComponent0 extends import1.AppView<import0.FooterComponent> {
  _el_0:any;
  compView_0:import1.AppView<import10.MdToolbar>;
  _MdToolbar_0_3:import11.Wrapper_MdToolbar;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import9.ViewContainer;
  _TemplateRef_4_5:any;
  _CustomIf_4_6:import12.Wrapper_CustomIf;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  /*private*/ _expr_17:any;
  _pipe_date_0:import13.DatePipe;
  _pipe_date_0_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent0,renderType_FooterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckOnce);
    this._expr_17 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'md-toolbar',new import3.InlineArray4(4,'class','footer-toolbar','color','accent'),(null as any));
    this.compView_0 = new import11.View_MdToolbar0(this.viewUtils,this,0,this._el_0);
    this._MdToolbar_0_3 = new import11.Wrapper_MdToolbar(new import15.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','navbar-text'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import9.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import16.TemplateRef_(this,4,this._anchor_4);
    this._CustomIf_4_6 = new import12.Wrapper_CustomIf(this._TemplateRef_4_5,this._vc_4.vcRef);
    this._text_5 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                       Weather in nearest places  \n                       ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-cloud right'),(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.compView_0.create(this._MdToolbar_0_3.context);
    this._pipe_date_0 = new import13.DatePipe(this.parentView.injectorGet(import17.LOCALE_ID,this.parentIndex));
    this._pipe_date_0_0 = import3.pureProxy2(this._pipe_date_0.transform.bind(this._pipe_date_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import18.CustomIf) && (4 === requestNodeIndex))) { return this._CustomIf_4_6.context; }
    if (((token === import10.MdToolbar) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdToolbar_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import14.ValueUnwrapper();
    const currVal_0_0_0:any = 'accent';
    this._MdToolbar_0_3.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdToolbar_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_4_0_0:any = ((this.context.today.getDate() === 25) && (this.context.today.getMonth() === 11));
    this._CustomIf_4_6.check_condition(currVal_4_0_0,throwOnChange,false);
    this._CustomIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    valUnwrapper.reset();
    const currVal_17:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_0_0,this._pipe_date_0.transform)(this.context.today,'longDate')),'\n                         ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_17,currVal_17))) {
      this.renderer.setText(this._text_3,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this.compView_0.destroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_FooterComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}