/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.footer-toolbar[_ngcontent-%COMP%]   md-toolbar-row[_ngcontent-%COMP%] {\r\n    justify-content: space-between;\r\n    color: white;\r\n}\r\n\r\n.glyphicon-cloud[_ngcontent-%COMP%] {\r\n    margin-left: 10px;\r\n}\r\n.right[_ngcontent-%COMP%] {\r\n    float: right; \r\n}'];