/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.loader[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    top: 64px;\r\n    bottom: 0;\r\n    left: 0;\r\n    right: 0;\r\n    background-color: #b0bec5;\r\n    z-index: 6;\r\n    color: white;\r\n}\r\n\r\np[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    font-size: 22px;\r\n    margin-top: 60px;\r\n}'];